name: kakao_flutter_mirror_example
description: Demonstrates how to use the kakao_flutter_mirror plugin.
version: 0.5.2
publish_to: "none"
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.20.0
  equatable: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  kakao_flutter_mirror:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/images/
